using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class RoomGenConfig : MonoBehaviour
{
    public static Dictionary<string, string[]> Room2Category = new Dictionary<string, string[]>
    {
        {"bedroom", new string[]{
        "bed", "deco", "accessory", "chair", "table", "bookcase", "cabinet", "desk",
        }},
        {"bathroom", new string[]{
        "bathroom", "deco", "bookcase",
        }},
        {"kitchen", new string[]{
        "kitchen", "table", "bookcase",
        }},
        {"studio", new string[]{
        "bed", "deco", "accessory", "chair", "table", "bookcase", "cabinet", "desk", "appliance",
        }},
        {"all", new string[]{}},

    };

    public static Dictionary<string, string[]> ItemsByCategory = new Dictionary<string, string[]>
    {
    {"bathroom", new string[]{
        "bathroomCabinet",
        "bathroomCabinetDrawer",
        "bathroomMirror",
        "bathroomSink",
        "bathroomSinkSquare",
        "bathtub",
        "toilet",
        "toiletSquare",
    }},
    {"bed", new string[]{
        "bedBunk",
        "bedDouble",
        "bedSingle",
    }},
    {"deco", new string[]{
        "trashcan",
        "bear",
        "ceilingFan",
        "coatRack",
        "coatRackStanding",
        "lampRoundFloor",
        "lampRoundTable",
        "lampSquareCeiling",
        "lampSquareFloor",
        "lampSquareTable",
        "lampWall",
        "paneling",
        "pillow",
        "pillowBlue",
        "pillowBlueLong",
        "pillowLong",
        "plantSmall1",
        "plantSmall2",
        "plantSmall3",
        "pottedPlant",
        "radio",
        "rugDoormat",
        "rugRectangle",
        "rugRound",
        "rugRounded",
        "rugSquare",
        "shower",
        "showerRound",
        "sideTable",
        "sideTableDrawers",
        "speaker",
        "speakerSmall",
    }},
    {"accessory", new string[]{
        "laptop",
        "computerKeyboard",
        "computerMouse",
        "computerScreen",
        "televisionAntenna",
        "televisionModern",
        "televisionVintage",
    }},
    {"chair", new string[]{
        "loungeChair",
        "loungeChairRelax",
        "loungeDesignChair",
        "loungeDesignSofa",
        "loungeDesignSofaCorner",
        "loungeSofa",
        "loungeSofaCorner",
        "loungeSofaLong",
        "loungeSofaOttoman",
        "bench",
        "benchCushion",
        "benchCushionLow",
        "chair",
        "chairCushion",
        "chairDesk",
        "chairModernCushion",
        "chairModernFrameCushion",
        "chairRounded",
        "stoolBar",
        "stoolBarSquare",
    }},
    {"bookcase", new string[]{
        "bookcaseClosed",
        "bookcaseClosedDoors",
        "bookcaseClosedWide",
        "bookcaseOpen",
        "bookcaseOpenLow",
        "books",
    }},
    { "cabinet", new string[]{
        "cabinetBed",
        "cabinetBedDrawer",
        "cabinetBedDrawerTable",
        "cabinetTelevision",
        "cabinetTelevisionDoors",
        "cardboardBoxClosed",
        "cardboardBoxOpen",
    }},
     {"desk", new string[]{
        "desk",
        "deskCorner",
    }},
     {"door", new string[]{
        "doorway",
        "doorwayFront",
        "doorwayOpen",
    }},
    {"appliance", new string[]{
        "dryer",
        "washer",
        "washerDryerStacked",
    }},
    {"floor", new string[]{
        "floorCorner",
        "floorCornerRound",
        "floorFull",
        "floorHalf",
    }},
    {"kitchen", new string[]{
        "toaster",
        "hoodLarge",
        "hoodModern",
        "kitchenBar",
        "kitchenBarEnd",
        "kitchenBlender",
        "kitchenCabinet",
        "kitchenCabinetCornerInner",
        "kitchenCabinetCornerRound",
        "kitchenCabinetDrawer",
        "kitchenCabinetUpper",
        "kitchenCabinetUpperCorner",
        "kitchenCabinetUpperDouble",
        "kitchenCabinetUpperLow",
        "kitchenCoffeeMachine",
        "kitchenFridge",
        "kitchenFridgeBuiltIn",
        "kitchenFridgeLarge",
        "kitchenFridgeSmall",
        "kitchenMicrowave",
        "kitchenSink",
        "kitchenStove",
        "kitchenStoveElectric",
    }},
    {"stairs", new string[]{
        "stairs",
        "stairsCorner",
        "stairsOpen",
        "stairsOpenSingle",
    }},
    {"table", new string[]{
        "table",
        "tableCloth",
        "tableCoffee",
        "tableCoffeeGlass",
        "tableCoffeeGlassSquare",
        "tableCoffeeSquare",
        "tableCross",
        "tableCrossCloth",
        "tableGlass",
        "tableRound",
    }},
   {"wall", new string[]{
        "wall",
        "wallCorner",
        "wallCornerRond",
        "wallDoorway",
        "wallDoorwayWide",
        "wallHalf",
        "wallWindow",
        "wallWindowSlide",
   }},
    };

}